apiVersion: v1
kind: Service
metadata:
  name: network-monitor-service
spec:
  type: NodePort
  selector:
    app: network-monitor
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30100
